### ISSUE TITLE
Bevezetőben elgépelés

### ISSUE THREAD

**Issue by Omcsesz** [rlegendi/ELTE-javagyak#4]
"A legtöbb programozási nyelv az 1985-ben elfogadott IEE 754 szabvány szerint kezeli a számokat, ezek alól a Java sem kivétel."

Az IEEE754 -ből kimaradt egy E.

**Comment by rlegendi** [comment]
Hi!

Thx, este meló után megnézem :-)

Btw ha épp átmész az anyagon, nyugodtan forkold, javítsd ezeket, és ha dobsz egy pull requestet, batchben megnézem merge-elem őket.

Üdv,
Ricsi

**Comment by rlegendi** [comment]
https://github.com/rlegendi/ELTE-javagyak/commit/cb039141431ef83c5367da7ffc51ce5e16b10bc0
